"""
Split the source question dataset to train/val/test splits.

Note that the resulting splits are further extended e.g. by
autogenerated questions, negations etc.
"""

import csv
import sys


def split(i):
    # val_split and test_split are 1/5 both
    splits = [
            'train',
            'val',
            'train',
            'train',
            'train',
            'test',
            'train',
            'train',
            'train',
            'train',
            ]
    return splits[i % len(splits)]


qlist = {'train': [], 'val': [], 'test': []}

cols = [-1, 0, 31, 30, 28, 29]
finalh = []

for csvfile in sys.argv[1:]:
    header = []
    for i, line in enumerate(csv.reader(open(csvfile, mode='rb'), delimiter=',', skipinitialspace=True)):
        if not header:
            header = line + ['origin']
            if not finalh:
                finalh = header
            continue
        i += 1
        if line[16] == 'Rejected':
            continue
        line[29] = line[29].replace('\n', ' ').replace('\t', ' ')  # all sorts of weird stuff appear in URL
        qlist[split(i)].append(line + ['MT'])

for sname in qlist.keys():
    with open('../q%s.tsv' % (sname,), 'wb') as csvfile:
        writer = csv.writer(csvfile, delimiter='\t')
        writer.writerow([finalh[c] for c in cols])
        for q in qlist[sname]:
            writer.writerow([q[c] for c in cols])
