"""
Split the source question dataset to train/val/test splits.

Note that the resulting splits are further extended e.g. by
autogenerated questions, negations etc.
"""

import csv
from fractions import gcd
import sys

split_ = [400, 150, 200]  # absolute or fraction of [train, val, test] split
gcd_ = gcd(split_[0], gcd(split_[1], split_[2]))
split_ = [x/gcd_ for x in split_]
s = sum(split_)
train_split = range(split_[0])
val_split = [split_[0]+x for x in range(split_[1])]


def split(i):
    if i % s in train_split:
        return 'train'
    elif i % s in val_split:
        return 'val'
    else:
        return 'test'


qlist = {'train': [], 'val': [], 'test': []}

cols = [-1, 0, 31, 30, 28, 29]
finalh = []

for csvfile in sys.argv[1:]:
    header = []
    for i, line in enumerate(csv.reader(open(csvfile), delimiter=',', skipinitialspace=True)):
        if not header:
            header = line + ['origin']
            if not finalh:
                finalh = header
            continue
        i += 1
        if line[16] == 'Rejected':
            continue
        line[29] = line[29].replace('\n', ' ').replace('\t', ' ')  # all sorts of weird stuff appear in URL
        qlist[split(i)].append(line + ['MT'])

for sname in qlist.keys():
    with open('../q%s.tsv' % (sname,), 'wb') as csvfile:
        writer = csv.writer(csvfile, delimiter='\t')
        writer.writerow([finalh[c] for c in cols])
        for q in qlist[sname]:
            writer.writerow([q[c] for c in cols])
